server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2ze33km15gw01e24zwo.mysql.rds.aliyuncs.com:3306/tax_verify?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: xxxx
    password: xxxx
    
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.ganen.tax: debug